
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Include:
    - 'lib/**/*'
  Exclude:
    - 'samples/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'

# I'm using it for control flow
Style/AndOr:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/FormatString:
  EnforcedStyle: percent

Style/Lambda:
  Enabled: false
  
# As it's about arrays, see? Arrays should be in square braces.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    ! '%w': ! '[]'

Style/StructInheritance:
  Enabled: false

# Some math just looks better this way
Layout/SpaceAroundOperators:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/BlockDelimiters:
  EnforcedStyle: semantic
  AllowBracesOnProceduralOneLiners: true

# Might have performance penalty
Style/NumericPredicate:
  Enabled: false

# I'm trying! Trying!
Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

# FIXME: maybe this one is not that fair
Metrics/AbcSize:
  Max: 20

